# @package _global_

original_work_dir: ${hydra:runtime.cwd}
eval_dir: ${original_work_dir}/pretrained/8k
output_dir: ${eval_dir}/outputs
ckpt: ${eval_dir}/checkpoints/epoch_049.ckpt

vctk_root: ${oc.env:VCTK_ROOT}
file_format: flac

test_spkers:
  - "p360"
  - "p361"
  - "p362"
  - "p363"
  - "p364"
  - "p374"
  - "p376"
  - "s5"
